### 1. Import the NUMPY package under the name np.

In [2]:
import numpy as np

### 2. Print the NUMPY version and the configuration.

In [3]:
print(np.__version__)

1.16.4


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
* Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
a = np.random.random((2,3,5))

In [29]:
a

array([[[0.3944389 , 0.10253048, 0.46572058, 0.97087772, 0.09848962],
        [0.47093544, 0.36606617, 0.99935297, 0.38311865, 0.4277311 ],
        [0.03177867, 0.72292646, 0.5510618 , 0.17009981, 0.6435816 ]],

       [[0.67477007, 0.28189785, 0.42352084, 0.68431125, 0.85281553],
        [0.25500574, 0.05734092, 0.24280272, 0.15178326, 0.15223495],
        [0.2942295 , 0.96580928, 0.98492843, 0.29920669, 0.62253078]]])

### 4. Print a.

In [5]:
print(a)

[[[0.3944389  0.10253048 0.46572058 0.97087772 0.09848962]
  [0.47093544 0.36606617 0.99935297 0.38311865 0.4277311 ]
  [0.03177867 0.72292646 0.5510618  0.17009981 0.6435816 ]]

 [[0.67477007 0.28189785 0.42352084 0.68431125 0.85281553]
  [0.25500574 0.05734092 0.24280272 0.15178326 0.15223495]
  [0.2942295  0.96580928 0.98492843 0.29920669 0.62253078]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [6]:
b = np.ones((5,2,3))

### 6. Print b.

In [7]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


### 7. Do a and b have the same size? How do you prove that in Python code?

In [8]:
if a.size == b.size:
    print("The arrays have the same size")
else:
    print("The arrays don`t have the same size")

The arrays have the same size


### 8. Are you able to add a and b? Why or why not?

In [9]:
soma = a + b
print('soma:\n', soma)

#No, we can`t cause they doont have the same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [10]:
c = b.reshape(2,3,5)
print(c)  

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


### 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [11]:
d = a + c
print('d:\n', d)

d:
 [[[1.3944389  1.10253048 1.46572058 1.97087772 1.09848962]
  [1.47093544 1.36606617 1.99935297 1.38311865 1.4277311 ]
  [1.03177867 1.72292646 1.5510618  1.17009981 1.6435816 ]]

 [[1.67477007 1.28189785 1.42352084 1.68431125 1.85281553]
  [1.25500574 1.05734092 1.24280272 1.15178326 1.15223495]
  [1.2942295  1.96580928 1.98492843 1.29920669 1.62253078]]]


In [12]:
# It works because the arrays has the same size

### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
print(a)

[[[0.3944389  0.10253048 0.46572058 0.97087772 0.09848962]
  [0.47093544 0.36606617 0.99935297 0.38311865 0.4277311 ]
  [0.03177867 0.72292646 0.5510618  0.17009981 0.6435816 ]]

 [[0.67477007 0.28189785 0.42352084 0.68431125 0.85281553]
  [0.25500574 0.05734092 0.24280272 0.15178326 0.15223495]
  [0.2942295  0.96580928 0.98492843 0.29920669 0.62253078]]]


In [14]:
print(d)

[[[1.3944389  1.10253048 1.46572058 1.97087772 1.09848962]
  [1.47093544 1.36606617 1.99935297 1.38311865 1.4277311 ]
  [1.03177867 1.72292646 1.5510618  1.17009981 1.6435816 ]]

 [[1.67477007 1.28189785 1.42352084 1.68431125 1.85281553]
  [1.25500574 1.05734092 1.24280272 1.15178326 1.15223495]
  [1.2942295  1.96580928 1.98492843 1.29920669 1.62253078]]]


In [15]:
#Each element from the array a had 1 added. 1 from the array b reshaped.

### 12. Multiply a and c. Assign the result to e.

In [16]:
e = a * c

In [17]:
print('multiplicar:\n', e)

multiplicar:
 [[[0.3944389  0.10253048 0.46572058 0.97087772 0.09848962]
  [0.47093544 0.36606617 0.99935297 0.38311865 0.4277311 ]
  [0.03177867 0.72292646 0.5510618  0.17009981 0.6435816 ]]

 [[0.67477007 0.28189785 0.42352084 0.68431125 0.85281553]
  [0.25500574 0.05734092 0.24280272 0.15178326 0.15223495]
  [0.2942295  0.96580928 0.98492843 0.29920669 0.62253078]]]


### 13. Does e equal to a? Why or why not?

In [18]:
#Yes, a is equal to e. When you multiply all the elements of the array a and for the elements in the array c, whose elements are all equivalent to 1, you'll have the same values.
e == a


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [19]:
d_max = d.max()

In [20]:
d_min = d.min()

In [21]:
d_mean = d.mean()

### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [27]:
f = np.empty([2,3,5])

In [28]:
f

array([[[0.3944389 , 0.10253048, 0.46572058, 0.97087772, 0.09848962],
        [0.47093544, 0.36606617, 0.99935297, 0.38311865, 0.4277311 ],
        [0.03177867, 0.72292646, 0.5510618 , 0.17009981, 0.6435816 ]],

       [[0.67477007, 0.28189785, 0.42352084, 0.68431125, 0.85281553],
        [0.25500574, 0.05734092, 0.24280272, 0.15178326, 0.15223495],
        [0.2942295 , 0.96580928, 0.98492843, 0.29920669, 0.62253078]]])


### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.


In [32]:
for i in range(2):
    for j in range(3):
        for k in range(5):
            
            if d[i,j,k]>d_min and d [i,j,k]<d_mean:
                f[i,j,k]=25
print(f)

[[[25.         25.          0.46572058  0.97087772 25.        ]
  [ 0.47093544 25.          0.99935297 25.         25.        ]
  [ 0.03177867  0.72292646  0.5510618  25.          0.6435816 ]]

 [[ 0.67477007 25.         25.          0.68431125  0.85281553]
  [25.         25.         25.         25.         25.        ]
  [25.          0.96580928  0.98492843 25.          0.62253078]]]


### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""
